---
- name: write kelleyk/emacs ppa key to /root
  copy:
    src: 873503A090750CDAEB0754D93FF0E01EEAAFC9CD.gpg
    dest: /root/873503A090750CDAEB0754D93FF0E01EEAAFC9CD.gpg
  sudo: yes

# TODO: Only do this for Ubuntu versions that need it
- name: add kelleyk/emacs ppa key to apt-key
  apt_key:
    file: /root/873503A090750CDAEB0754D93FF0E01EEAAFC9CD.gpg
  sudo: yes

- name: kelleyk sources.list
  template: >
    src=kelleyk-emacs.list.j2
    dest=/etc/apt/sources.list.d/kelleyk-emacs.list
    force=no
  register: sources_list_result
  sudo: yes

# TODO: Only do this for Ubuntu versions that need it
- name: apt-get update
  apt: update_cache=true cache_valid_time=0
  when: sources_list_result.changed
  sudo: yes
