version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: sudo apt-get update -qq
      - run: sudo apt-get install -y wget make ruby-bundler python-virtualenv
      # Needed to upgrade requests[security] on Ubuntu 14.04
      - run: sudo apt-get install -y python-dev libffi-dev libssl-dev
      - run: sudo apt-get install -y docker.io
      # Run test
      # Cannot use fedora:20 image due to
      # https://fedorahosted.org/spin-kickstarts/ticket/55
      - run: >
          wget -O- bit.ly/ansibletest | env
          ANSIBLE_VERSIONS="1.4 1.5.4 1.7.2 1.9.2 2.0.0.2 2.1.0.0
          2.2.1.0"
          DOCKER_IMAGES="centos:6 centos:7 fedora:21 fedora:23
          ubuntu:14.04 ubuntu:16.04"
          sh -x
      - run:
          name: cat fake-role-no-tests .kitchen/logs/kitchen.log
          command: cat fake-role-no-tests/role-tester/.kitchen/logs/kitchen.log
          when: on_fail
